clear all
close all
clc

% Parameters for electrodes creation
MaxRad = 1;
EfectiveSurfFact = 0.65;
ElectGrid = 5;
ElectWidth = 0.14;
ElectCorner00 = EfectiveSurfFact*MaxRad/sqrt(2);
ElectSpace = (EfectiveSurfFact*MaxRad/sqrt(2)-ElectWidth...
                + EfectiveSurfFact*MaxRad/sqrt(2))/(ElectGrid-1);

% Arraz where each row is an electrode in format (x1 x2 y1 y2)
ElectCorners = zeros(ElectGrid^2,4);
for k = 1:ElectGrid  % These are the rows
    for l = 1:ElectGrid % These are the columns
        ElectCorners(l+(k-1)*ElectGrid,1) = -ElectCorner00            + (l-1)*ElectSpace;
        ElectCorners(l+(k-1)*ElectGrid,2) = -ElectCorner00+ElectWidth + (l-1)*ElectSpace;
        ElectCorners(l+(k-1)*ElectGrid,3) =  ElectCorner00-ElectWidth - (k-1)*ElectSpace;
        ElectCorners(l+(k-1)*ElectGrid,4) =  ElectCorner00            - (k-1)*ElectSpace;
        plot([ElectCorners(l+(k-1)*ElectGrid,1),...
                    ElectCorners(l+(k-1)*ElectGrid,2)],...
                [ElectCorners(l+(k-1)*ElectGrid,3),...
                    ElectCorners(l+(k-1)*ElectGrid,3)],...
                'k'); hold on;
        plot([ElectCorners(l+(k-1)*ElectGrid,2),...
                    ElectCorners(l+(k-1)*ElectGrid,2)],...
                [ElectCorners(l+(k-1)*ElectGrid,3),...
                    ElectCorners(l+(k-1)*ElectGrid,4)],...
                'k'); hold on;
        plot([ElectCorners(l+(k-1)*ElectGrid,2),...
                    ElectCorners(l+(k-1)*ElectGrid,1)],...
                [ElectCorners(l+(k-1)*ElectGrid,4),...
                    ElectCorners(l+(k-1)*ElectGrid,4)],...
                'k'); hold on;
        plot([ElectCorners(l+(k-1)*ElectGrid,1),...
                    ElectCorners(l+(k-1)*ElectGrid,1)],...
                [ElectCorners(l+(k-1)*ElectGrid,4),...
                    ElectCorners(l+(k-1)*ElectGrid,3)],...
                'k'); hold on;
    end
end
x = linspace(-MaxRad,MaxRad,100);
plot(x,sqrt(MaxRad^2-x.^2),'k'); hold on;
plot(x,-sqrt(MaxRad^2-x.^2),'k'); hold off;
axis square